is_array() is expensive
ADOdb/ADOdb pull request #760
Opened 2021-09-27 02:29 UTC by Unifex

The call to `pg_fetch_array()` returns `false` in all cases where we wouldn't need or want to potentially `_fixblobs()` and return `true`.

A straight up boolean check is all that is needed here.

2021-10-15 07:48 UTC, dregad requested changes
Thanks for your contribution.

I have no objections with the change, but considering that this usage of is_array() is also present in the _ADORecordSet_assoc_postgres7_ as well as in the parent _ADORecordSet_postgres64_ classes' _fetch() and MoveNext() methods, I believe it should be changed there as well.

2021-10-21 01:04 UTC, Unifex commented
I'll take a run at that this weekend.  Thanks for spotting the other spots.

2021-11-05 01:49 UTC, Unifex commented
Hello @dregad, sorry for not getting to this earlier.  Life happens unfortunately.  Upside though, I got some time from my employer to finish this up.  Looking at the other places this would have been updated resulted in more refactoring than anticipated but I think it makes things much more readable and removes a lot of repeated code.

I was also thinking that the request to `$this->fields = @pg_fetch_array($this->_queryID,$this->_currentRow,$this->fetchMode);` could also be moved into `_fixblobs()` but at this point that method would be doing a lot more than what its name suggests.  If there is confidence that third party code isn't reliant on it it could be renamed to `_prepfields()` and the `pg_fetch_array()` line moved there too.

2021-11-05 02:14 UTC, Unifex commented
@dregad, I went ahead and pushed an extra branch to explore the `_prepfields()` approach should you want to go down that route.  It is on #767.

2021-11-05 07:30 UTC, dregad commented
> sorry for not getting to this earlier. Life happens unfortunately.

No worries... Trust me, I know what it's like :wink: 

As a matter of fact, I got delayed as well and did not release 5.22.0 last week-end as planned either... I'll review your PRs, hopefully by tomorrow.

2021-11-08 17:37 UTC, dregad commented
Closed in favor of #767

2021-11-08 17:37 UTC, closed without merging