PHPStan error fixes
ADOdb/ADOdb pull request #778
Opened 2021-12-17 03:10 UTC by dianne-tennent

This patch fixes some errors detected by a phpstan analysis at
level 0. This doesn't cover the entire directory, only the
files in this patch, as unfortunately I have no more time available.

It addresses errors such as:
 - Access to an undefined property
 - Call to an undefined method

2021-12-17 03:10 UTC, dianne-tennent commented
Just going to redo this with only one commit

2022-01-05 00:32 UTC, dregad requested changes
This can't be merged in its current state.

PHPDoc blocks must be formatted with a space before the `*`, i.e.
  ```
  /**
  * BAD
  */

  /**
   * CORRECT
   */
  ```

2022-01-05 00:32 UTC, dregad commented on adodb-memcache.lib.inc.php
> +				else ADOConnection::outp("flushcache: $filename entry flushed from memcache server!<br>\n");
Why add this ? It's the same logic as the test just below, and the $filename variable referenced in the message does not exist.

Also: incorrect indentation level and code does not follow guidelines

2022-01-05 00:32 UTC, dregad commented on adodb-pear.inc.php
> +		if (!is_object($obj)) $obj = ADODB_Error_PEAR($type, 'CONNECT', -1, 'Unknown Database Driver: '.$type);
This is wrong. ADODB_Error_PEAR() does not return a value.

2022-01-05 00:32 UTC, dregad commented on adodb-pear.inc.php
> +			$obj = ADODB_Error_PEAR($type, 'CONNECT', -1, 'Unknown Database Driver: '.$dsninfo['phptype']);
ditto

2022-01-05 00:32 UTC, dregad commented on adodb-xmlschema.inc.php
> +	*/
OK but please keep 1 space before the `*` on PHPDoc blocks

2022-01-05 00:32 UTC, dregad commented on adodb.inc.php
> +	function _connect($argHostname = "", $argUsername = "", $argPassword = "", $argDatabaseName = "", $forceNew = false) {
You can't do that ! 

connect() is ADOdb's main connection public method, which relies on driver-specific, protected _connect().

All changes to connect(), nconnect(), pconnect() must be undone.

2022-01-05 00:32 UTC, dregad commented on adodb.inc.php
> +			$this->_queryID = @$this->Query($sql,$inputarr);
Same comment as for connect() - query() is the public interface function, _query() is the driver-specific

2022-01-05 00:32 UTC, dregad commented on adodb.inc.php
> +
This introduces a syntax error 
> PHP Fatal error:  Cannot redeclare ADORecordSet::_initRS() in adodb.inc.php on line 3974

Not sure why you are redefining _initRS() and _fetch() methods... And where is this code coming from ?

2022-01-14 15:49 UTC, dregad commented
Since you did not respond to my review, I'm going to close this without merging; feel free to reopen if you wish to reply to my comments or update the PR.

2022-01-14 15:49 UTC, closed without merging

2022-01-18 01:57 UTC, dianne-tennent commented
Thanks for the code review @dregad - and my apologies for the errors. I obviously wasn't testing properly at our end. Happy to leave this closed. I have a smaller patch that we are hoping to include in our repo, so will make another pull request with that one if that's okay. Cheers, Dianne

2022-01-18 06:42 UTC, dregad commented
> smaller patch that we are hoping to include in our repo, so will make another pull request with that one if that's okay

By all means do submit, your contributions are welcome!