Fix PHP8.2 compatitibility issues:-
ADOdb/ADOdb pull request #917
Opened 2023-01-07 15:58 UTC by reportico-web

Fatal Error: drivers/adodb-pdo.inc.php Line 605 - Creation of dynamic property ADODB_pdo::$_stmt is deprecated
Fatal Error: drivers/adodb-pdo.inc.php Line 788 - Creation of dynamic property ADORecordSet_pdo::$adodbFetchMode is deprecated

2023-01-16 14:55 UTC, dregad requested changes
@reportico-web Thanks for your contribution.

2023-01-16 14:55 UTC, dregad commented on composer.json
> +	"name" : "reportico/adodb-php",
This does not belong in the pull request. Please remove.

2023-01-16 17:50 UTC, Bozosoft commented
Sorry but I don't use the drivers/adodb-pdo.inc.php ;)
I have only in drivers/  adodb-postgres...  and  adodb-mysqli.inc.php
So the problem is confirmed for me on adodb-postgres64.inc.php

2023-01-17 07:18 UTC, dregad commented
@Bozosoft see my note https://github.com/ADOdb/ADOdb/issues/913#issuecomment-1384392562

2023-01-18 23:50 UTC, closed without merging

2023-01-19 00:04 UTC, dregad commented
Merged in 6486f117d9cba8d532ef6adfb92f3ccd515c805b