Nathan gibbs3 issue#978
ADOdb/ADOdb pull request #979
Opened 2023-06-10 02:20 UTC by NathanGibbs3

Fixes Issue #978

2023-06-10 14:27 UTC, dregad requested changes
Thanks for your contribution. Review comments:

Please follow our coding guidelines (PSR-2 / 12) in submitted code.

This is a bug, so should be targeted at hotfix/5.22 branch; if you could change target and rebase your branch accordingly, it would be great.

2023-06-10 14:27 UTC, dregad commented on drivers/adodb-postgres8.inc.php
> +				);
No need to wrap if line length < 120

2023-06-10 15:07 UTC, NathanGibbs3 commented
I knew there would be some changes, working on those.

> Please follow our coding guidelines (PSR-2 / 12) in submitted code.
> 

Is there a PHPCodeSniffer rule set somewhere in the repo that I can run against my changes to make sure they are aligned with your coding standards?
I am not very familiar with the PSR standards, so having something to auto check things would be great.

> This is a bug, so should be targeted at hotfix/5.22 branch; if you could change target and rebase your branch accordingly, it would be great.

Not a Git Ninja here, I may need a little help.
I need to figure out the following.
- How to pull the hotfix/5.22 branch into my github fork of ADOdb, so that I can pull it down locally
- I have no idea what you meant about rebasing my branch.
- Change the target branch of this PR.

I don't know what I don't know, so I'm letting you know what I don't know. 
I'll try to figure it all out.

2023-06-10 15:09 UTC, NathanGibbs3 commented on drivers/adodb-postgres8.inc.php
> +		$result = @$this->GetOne($tmpsql);
I borrowed the suppression operator idea from the mysqli driver's implementation of the same functionality. It may not work over there either.

2023-06-10 15:16 UTC, NathanGibbs3 commented
I think I have all of the code specific changes, I just need to figure out how to get them to the right branch. and adjust this PR.

2023-06-10 16:20 UTC, dregad commented
> Is there a PHPCodeSniffer rule set somewhere

That's a work in progress. You'll find the current state of things at https://github.com/dregad/ADOdb/blob/codesniffer/phpcs.xml.dist if that helps.

At the moment the code base is not clean enough that I can easily run the tool against it, and it's a low-priority thing so...

> How to pull the hotfix/5.22 branch into my github fork of ADOdb, so that I can pull it down locally

```
git remote add upstream git@github.com:ADOdb/ADOdb.git
git fetch upstream
```

> I have no idea what you meant about rebasing my branch.

Your feature branch is based on _master_. The idea is to move the branch to be on top of _hotfix/5.22_ instead. There's several ways to do this, what I usually do is `git rebase <current tip> <feature branch> --onto <target branch>`, so for you probably something like this should do the trick

```
git rebase master NathanGibbs3:NathanGibbs3-Issue#978 --onto hotfix/5.22
```

Then (assuming you have the branch tracking your Github fork):
```
git push --force 
```

> Change the target branch of this PR.

That's the easiest part, just click the _Edit_ button next to the pull request's title and change the _base_
![image](https://github.com/ADOdb/ADOdb/assets/449891/0602f052-2671-4ff1-ba70-6528842ea083)

Let me know if you need more help

2023-06-10 16:21 UTC, dregad commented
And if that sounds too difficult, forget about it I can do it myself too

2023-06-10 17:22 UTC, NathanGibbs3 commented
I was able to add upstream, but can't fetch it.

> git fetch upstream

Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch upstream

2023-06-10 17:23 UTC, NathanGibbs3 commented
> And if that sounds too difficult, forget about it I can do it myself too

I value the learning experience. Not an issue.
It's part of git that I haven't used before.

2023-06-10 17:28 UTC, NathanGibbs3 commented
> I was able to add upstream, but can't fetch it.
> 
> > git fetch upstream
> 
> Permission denied (publickey). fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights and the repository exists. error: Could not fetch upstream

Got it needed to `git remote add upstream https://github.com/ADOdb/ADOdb.git`

2023-06-10 18:39 UTC, NathanGibbs3 commented
I "think" we are good to go.
Give my work another once over before merging, if there are still issues, I'll fix them.
Do I need to remove the error suppressor from my code?
That's all I can think of at the moment.

2023-06-10 19:39 UTC, NathanGibbs3 commented on drivers/adodb-postgres8.inc.php
> +		$result = @$this->GetOne($tmpsql);
Does the closure of #981 close this issue with the PR as well?

2023-06-10 20:35 UTC, NathanGibbs3 commented
> That's a work in progress. You'll find the current state of things at https://github.com/dregad/ADOdb/blob/codesniffer/phpcs.xml.dist if that helps.
> 
> At the moment the code base is not clean enough that I can easily run the tool against it, and it's a low-priority thing so..

Here is a piece of phpcs.xml that may help based on  the conversations here & the `.editorconfig` file from the repo.

```xml
    <arg name="tab-width" value="4"/>
    <rule ref="Generic.WhiteSpace">
        <exclude name="Generic.WhiteSpace.DisallowTabIndent.TabsUsed" />
        <rule ref="Generic.WhiteSpace.ScopeIndent">
            <properties>
                <property name="tabIndent" value="true" />
            </properties>
        </rule>
    </rule>
    <rule ref="Generic.Files.LineLength">
        <properties>
            <property name="lineLimit" value="120" />
            <property name="absoluteLineLimit" value="120" />
        </properties>
    </rule>
```

2023-06-10 22:50 UTC, dregad commented on drivers/adodb-postgres8.inc.php
> +		$result = @$this->GetOne($tmpsql);
It should, yes

2023-06-10 22:56 UTC, dregad commented
> Give my work another once over before merging, if there are still issues, I'll fix them.

Will do. Thanks for your efforts, I appreciate the collaboration on this

> Do I need to remove the error suppressor from my code?

No, with the fix for #981 it's necessary to prevent an exception from being thrown when the `SELECT lastval()` fails.

2023-06-10 23:31 UTC, dregad approved these changes
- Missing declaration for $ADODB_GETONE_EOF global
- A few coding guidelines issues
- A comment explaining the reason for using `@` would be useful

I'll fix those myself with a follow-up commit.

Thanks

2023-06-10 23:43 UTC, merged

2023-06-11 00:12 UTC, NathanGibbs3 commented
> * Missing declaration for $ADODB_GETONE_EOF global
> 

I can't believe I missed that. 🤦‍♂️ 

>  * A few coding guidelines issues
> 
> * A comment explaining the reason for using `@` would be useful
> 
> 
> I'll fix those myself with a follow-up commit.
> 

OK, I see what you mean.
I checked out your follow up commit.  I will keep that in mind if I submit any PR's in the future.
Anything to make merging easier.

> Thanks

You are most welcome, thank you for maintaining ADOdb. :smile:
Also, thank you for the pointers on git rebase, etc.  I learned a few things today. 👍 😄